#!/usr/bin/env python
#-*- coding:utf-8 -*-

"""
This file is part of OpenSesame.

OpenSesame is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

OpenSesame is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with OpenSesame.  If not, see <http://www.gnu.org/licenses/>.
"""

import os
import os.path
from PyQt4 import QtGui, QtCore
import sys
import libqtopensesame.qtopensesame
import libopensesame.misc		
import time

if __name__ == "__main__":

	libopensesame.misc.change_working_dir()

	app = QtGui.QApplication(sys.argv)	
	
	# Show the splash screen
	splash = QtGui.QSplashScreen(QtGui.QPixmap(libopensesame.misc.resource("splash.png")), QtCore.Qt.WindowStaysOnTopHint)
	splash.show()	
	app.processEvents()
		
	myapp = libqtopensesame.qtopensesame.qtopensesame()
	QtCore.QObject.connect(app, QtCore.SIGNAL("quit()"), myapp.close)		
	
	myapp.show()	
	
	# Wait and hide the splash
	#t = time.time()	
	#while time.time() - t < 0.5:
	#	app.processEvents()	
	splash.finish(myapp)
	
	# Open an experiment if it has been specified as a command
	# line argument
	if len(sys.argv) >= 2 and os.path.isfile(sys.argv[1]):
		myapp.open_file(path = sys.argv[1])
		
	# Run the experiment if it has been specified on the
	# command line
	if myapp.options.run:
		myapp.run_experiment()
	elif myapp.options.run_in_window:
		myapp.run_experiment(False)
	else:	
		myapp.check_update(always = False)	
		myapp.show_random_tip(always = False)	
		
	sys.exit(app.exec_())
