# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/ui/backend_settings.ui'
#
# Created: Sat Jul 14 17:34:56 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_widget_backend_settings(object):
    def setupUi(self, widget_backend_settings):
        widget_backend_settings.setObjectName(_fromUtf8("widget_backend_settings"))
        widget_backend_settings.resize(828, 852)
        self.verticalLayout = QtGui.QVBoxLayout(widget_backend_settings)
        self.verticalLayout.setMargin(4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.scrollarea_backend_settings = QtGui.QScrollArea(widget_backend_settings)
        self.scrollarea_backend_settings.setWidgetResizable(True)
        self.scrollarea_backend_settings.setObjectName(_fromUtf8("scrollarea_backend_settings"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 818, 842))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.widget_2 = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setSpacing(16)
        self.horizontalLayout.setMargin(4)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_backend_icon = QtGui.QLabel(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_backend_icon.sizePolicy().hasHeightForWidth())
        self.label_backend_icon.setSizePolicy(sizePolicy)
        self.label_backend_icon.setObjectName(_fromUtf8("label_backend_icon"))
        self.horizontalLayout.addWidget(self.label_backend_icon)
        self.label_2 = QtGui.QLabel(self.widget_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout_7.addWidget(self.widget_2)
        self.group_canvas = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.group_canvas.setObjectName(_fromUtf8("group_canvas"))
        self.layout_canvas = QtGui.QVBoxLayout(self.group_canvas)
        self.layout_canvas.setContentsMargins(0, -1, 0, 0)
        self.layout_canvas.setObjectName(_fromUtf8("layout_canvas"))
        self.label_canvas = QtGui.QLabel(self.group_canvas)
        self.label_canvas.setObjectName(_fromUtf8("label_canvas"))
        self.layout_canvas.addWidget(self.label_canvas)
        self.verticalLayout_7.addWidget(self.group_canvas)
        self.group_keyboard = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.group_keyboard.setObjectName(_fromUtf8("group_keyboard"))
        self.layout_keyboard = QtGui.QVBoxLayout(self.group_keyboard)
        self.layout_keyboard.setContentsMargins(0, -1, 0, 0)
        self.layout_keyboard.setObjectName(_fromUtf8("layout_keyboard"))
        self.label_keyboard = QtGui.QLabel(self.group_keyboard)
        self.label_keyboard.setObjectName(_fromUtf8("label_keyboard"))
        self.layout_keyboard.addWidget(self.label_keyboard)
        self.verticalLayout_7.addWidget(self.group_keyboard)
        self.group_mouse = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.group_mouse.setObjectName(_fromUtf8("group_mouse"))
        self.layout_mouse = QtGui.QVBoxLayout(self.group_mouse)
        self.layout_mouse.setContentsMargins(0, -1, 0, 0)
        self.layout_mouse.setObjectName(_fromUtf8("layout_mouse"))
        self.label_mouse = QtGui.QLabel(self.group_mouse)
        self.label_mouse.setObjectName(_fromUtf8("label_mouse"))
        self.layout_mouse.addWidget(self.label_mouse)
        self.verticalLayout_7.addWidget(self.group_mouse)
        self.group_sampler = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.group_sampler.setObjectName(_fromUtf8("group_sampler"))
        self.layout_sampler = QtGui.QVBoxLayout(self.group_sampler)
        self.layout_sampler.setContentsMargins(0, -1, 0, 0)
        self.layout_sampler.setObjectName(_fromUtf8("layout_sampler"))
        self.label_sampler = QtGui.QLabel(self.group_sampler)
        self.label_sampler.setObjectName(_fromUtf8("label_sampler"))
        self.layout_sampler.addWidget(self.label_sampler)
        self.verticalLayout_7.addWidget(self.group_sampler)
        self.group_synth = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.group_synth.setObjectName(_fromUtf8("group_synth"))
        self.layout_synth = QtGui.QVBoxLayout(self.group_synth)
        self.layout_synth.setContentsMargins(0, -1, 0, 0)
        self.layout_synth.setObjectName(_fromUtf8("layout_synth"))
        self.label_synth = QtGui.QLabel(self.group_synth)
        self.label_synth.setObjectName(_fromUtf8("label_synth"))
        self.layout_synth.addWidget(self.label_synth)
        self.verticalLayout_7.addWidget(self.group_synth)
        self.widget = QtGui.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_7.addWidget(self.widget)
        self.scrollarea_backend_settings.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollarea_backend_settings)

        self.retranslateUi(widget_backend_settings)
        QtCore.QMetaObject.connectSlotsByName(widget_backend_settings)

    def retranslateUi(self, widget_backend_settings):
        widget_backend_settings.setWindowTitle(QtGui.QApplication.translate("widget_backend_settings", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_backend_icon.setText(QtGui.QApplication.translate("widget_backend_settings", "ICON", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("widget_backend_settings", "<b>Back-end settings</b><br />\n"
"Various settings related to the control of the display, sound, and input devices", None, QtGui.QApplication.UnicodeUTF8))
        self.group_canvas.setTitle(QtGui.QApplication.translate("widget_backend_settings", "Canvas", None, QtGui.QApplication.UnicodeUTF8))
        self.label_canvas.setText(QtGui.QApplication.translate("widget_backend_settings", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.group_keyboard.setTitle(QtGui.QApplication.translate("widget_backend_settings", "Keyboard", None, QtGui.QApplication.UnicodeUTF8))
        self.label_keyboard.setText(QtGui.QApplication.translate("widget_backend_settings", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.group_mouse.setTitle(QtGui.QApplication.translate("widget_backend_settings", "Mouse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_mouse.setText(QtGui.QApplication.translate("widget_backend_settings", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.group_sampler.setTitle(QtGui.QApplication.translate("widget_backend_settings", "Sampler", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sampler.setText(QtGui.QApplication.translate("widget_backend_settings", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.group_synth.setTitle(QtGui.QApplication.translate("widget_backend_settings", "Synth", None, QtGui.QApplication.UnicodeUTF8))
        self.label_synth.setText(QtGui.QApplication.translate("widget_backend_settings", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))

