.\" DO NOT MODIFY THIS FILE!  It was generated by help2man 1.40.4.
.TH 0.27 "1" "December 2012" "0.27 'Frisky Freud'" "User Commands"
.SH NAME
0.27 \- manual page for 0.27 'Frisky Freud'
.SH SYNOPSIS
.B opensesamerun
[\fIexperiment\fR] [\fIoptions\fR]
.SH OPTIONS
.TP
\fB\-\-version\fR
show program's version number and exit
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.IP
Subject and log file options:
.TP
\fB\-s\fR SUBJECT, \fB\-\-subject\fR=\fISUBJECT\fR
Subject number
.TP
\fB\-l\fR LOGFILE, \fB\-\-logfile\fR=\fILOGFILE\fR
Logfile
.IP
Display options:
.TP
\fB\-f\fR, \fB\-\-fullscreen\fR
Run fullscreen
.TP
\fB\-c\fR, \fB\-\-custom_resolution\fR
Do not use the display resolution specified in the
experiment file
.TP
\fB\-w\fR WIDTH, \fB\-\-width\fR=\fIWIDTH\fR
Display width
.TP
\fB\-e\fR HEIGHT, \fB\-\-height\fR=\fIHEIGHT\fR
Display height
.IP
Miscellaneous options:
.TP
\fB\-d\fR, \fB\-\-debug\fR
Print lots of debugging messages to the standard
output
.TP
\fB\-\-stack\fR
Print stack information
.IP
Miscellaneous options:
.TP
\fB\-\-pylink\fR
Load PyLink before PyGame (necessary for using the
Eyelink plug\-ins in non\-dummy mode)
.SH "SEE ALSO"
The full documentation for
.B 0.27
is maintained as a Texinfo manual.  If the
.B info
and
.B 0.27
programs are properly installed at your site, the command
.IP
.B info 0.27
.PP
should give you access to the complete manual.
