# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/opensesame.ui'
#
# Created: Fri Nov 11 12:19:17 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1000, 707)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "OpenSesame", None, QtGui.QApplication.UnicodeUTF8))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/experiment.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.tabwidget = QtGui.QTabWidget(self.centralwidget)
        self.tabwidget.setTabsClosable(True)
        self.tabwidget.setMovable(True)
        self.tabwidget.setObjectName(_fromUtf8("tabwidget"))
        self.verticalLayout_6.addWidget(self.tabwidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_file = QtGui.QMenu(self.menubar)
        self.menu_file.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_file.setObjectName(_fromUtf8("menu_file"))
        self.menu_recent_files = QtGui.QMenu(self.menu_file)
        self.menu_recent_files.setTitle(QtGui.QApplication.translate("MainWindow", "Recent files", None, QtGui.QApplication.UnicodeUTF8))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/recent_large.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_recent_files.setIcon(icon1)
        self.menu_recent_files.setObjectName(_fromUtf8("menu_recent_files"))
        self.menu_run = QtGui.QMenu(self.menubar)
        self.menu_run.setTitle(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_run.setObjectName(_fromUtf8("menu_run"))
        self.menu_items = QtGui.QMenu(self.menubar)
        self.menu_items.setTitle(QtGui.QApplication.translate("MainWindow", "Items", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_items.setObjectName(_fromUtf8("menu_items"))
        self.menu_view = QtGui.QMenu(self.menubar)
        self.menu_view.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_view.setObjectName(_fromUtf8("menu_view"))
        self.menu_help = QtGui.QMenu(self.menubar)
        self.menu_help.setTitle(QtGui.QApplication.translate("MainWindow", "Help and feedback", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_help.setObjectName(_fromUtf8("menu_help"))
        self.menu_tools = QtGui.QMenu(self.menubar)
        self.menu_tools.setTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_tools.setObjectName(_fromUtf8("menu_tools"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = statusbar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.dock_overview = QtGui.QDockWidget(MainWindow)
        self.dock_overview.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dock_overview.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Overview", None, QtGui.QApplication.UnicodeUTF8))
        self.dock_overview.setObjectName(_fromUtf8("dock_overview"))
        self.dock_widget_overview = QtGui.QWidget()
        self.dock_widget_overview.setObjectName(_fromUtf8("dock_widget_overview"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dock_widget_overview)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.itemtree = tree_overview(self.dock_widget_overview)
        self.itemtree.setMinimumSize(QtCore.QSize(200, 0))
        self.itemtree.setAcceptDrops(True)
        self.itemtree.setAlternatingRowColors(True)
        self.itemtree.setAutoExpandDelay(4)
        self.itemtree.setAnimated(True)
        self.itemtree.setHeaderHidden(True)
        self.itemtree.setObjectName(_fromUtf8("itemtree"))
        self.itemtree.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.itemtree.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout.addWidget(self.itemtree)
        self.dock_overview.setWidget(self.dock_widget_overview)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dock_overview)
        self.dock_variable_inspector = QtGui.QDockWidget(MainWindow)
        self.dock_variable_inspector.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dock_variable_inspector.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Variable inspector", None, QtGui.QApplication.UnicodeUTF8))
        self.dock_variable_inspector.setObjectName(_fromUtf8("dock_variable_inspector"))
        self.dock_widget_variable_inspector = QtGui.QWidget()
        self.dock_widget_variable_inspector.setObjectName(_fromUtf8("dock_widget_variable_inspector"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dock_widget_variable_inspector)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.widget_2 = QtGui.QWidget(self.dock_widget_variable_inspector)
        self.widget_2.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: #729fcf;"))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setMargin(4)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setPixmap(QtGui.QPixmap(_fromUtf8(":/icons/variable_inspector_large.png")))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Variable inspector", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget = QtGui.QWidget(self.dock_widget_variable_inspector)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.widget)
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8(":/icons/variable_inspector.png")))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.edit_variable_filter = QtGui.QLineEdit(self.widget)
        self.edit_variable_filter.setToolTip(QtGui.QApplication.translate("MainWindow", "Enter a filter", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_variable_filter.setObjectName(_fromUtf8("edit_variable_filter"))
        self.horizontalLayout_2.addWidget(self.edit_variable_filter)
        self.button_variables_clear = QtGui.QPushButton(self.widget)
        self.button_variables_clear.setToolTip(QtGui.QApplication.translate("MainWindow", "Clear filter", None, QtGui.QApplication.UnicodeUTF8))
        self.button_variables_clear.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/clear.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_variables_clear.setIcon(icon2)
        self.button_variables_clear.setIconSize(QtCore.QSize(16, 16))
        self.button_variables_clear.setObjectName(_fromUtf8("button_variables_clear"))
        self.horizontalLayout_2.addWidget(self.button_variables_clear)
        self.button_help_variables = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_help_variables.sizePolicy().hasHeightForWidth())
        self.button_help_variables.setSizePolicy(sizePolicy)
        self.button_help_variables.setToolTip(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.button_help_variables.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/help.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_help_variables.setIcon(icon3)
        self.button_help_variables.setIconSize(QtCore.QSize(16, 16))
        self.button_help_variables.setFlat(False)
        self.button_help_variables.setObjectName(_fromUtf8("button_help_variables"))
        self.horizontalLayout_2.addWidget(self.button_help_variables)
        self.verticalLayout_2.addWidget(self.widget)
        self.table_variables = variable_inspector(self.dock_widget_variable_inspector)
        self.table_variables.setAlternatingRowColors(True)
        self.table_variables.setShowGrid(True)
        self.table_variables.setGridStyle(QtCore.Qt.DotLine)
        self.table_variables.setObjectName(_fromUtf8("table_variables"))
        self.table_variables.setColumnCount(3)
        self.table_variables.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("MainWindow", "Variable", None, QtGui.QApplication.UnicodeUTF8))
        self.table_variables.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.table_variables.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("MainWindow", "In item", None, QtGui.QApplication.UnicodeUTF8))
        self.table_variables.setHorizontalHeaderItem(2, item)
        self.table_variables.horizontalHeader().setSortIndicatorShown(True)
        self.table_variables.horizontalHeader().setStretchLastSection(True)
        self.table_variables.verticalHeader().setVisible(False)
        self.table_variables.verticalHeader().setCascadingSectionResizes(True)
        self.verticalLayout_2.addWidget(self.table_variables)
        self.dock_variable_inspector.setWidget(self.dock_widget_variable_inspector)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dock_variable_inspector)
        self.dock_pool = QtGui.QDockWidget(MainWindow)
        self.dock_pool.setWindowTitle(QtGui.QApplication.translate("MainWindow", "File pool", None, QtGui.QApplication.UnicodeUTF8))
        self.dock_pool.setObjectName(_fromUtf8("dock_pool"))
        self.dock_pool_widget = QtGui.QWidget()
        self.dock_pool_widget.setObjectName(_fromUtf8("dock_pool_widget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dock_pool_widget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.dock_pool.setWidget(self.dock_pool_widget)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dock_pool)
        self.dock_stdout = QtGui.QDockWidget(MainWindow)
        self.dock_stdout.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.dock_stdout.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Debug window", None, QtGui.QApplication.UnicodeUTF8))
        self.dock_stdout.setObjectName(_fromUtf8("dock_stdout"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.widget_4 = QtGui.QWidget(self.dockWidgetContents_3)
        self.widget_4.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: #729fcf;"))
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_5.setMargin(4)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_5 = QtGui.QLabel(self.widget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setPixmap(QtGui.QPixmap(_fromUtf8(":/icons/stdout_large.png")))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.label_4 = QtGui.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Debug window", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.verticalLayout_4.addWidget(self.widget_4)
        self.widget_5 = QtGui.QWidget(self.dockWidgetContents_3)
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget_5)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.edit_stdout = console(self.widget_5)
        self.edit_stdout.setReadOnly(False)
        self.edit_stdout.setObjectName(_fromUtf8("edit_stdout"))
        self.horizontalLayout_6.addWidget(self.edit_stdout)
        self.widget_3 = QtGui.QWidget(self.widget_5)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.widget_3)
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.button_help_stdout = QtGui.QPushButton(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_help_stdout.sizePolicy().hasHeightForWidth())
        self.button_help_stdout.setSizePolicy(sizePolicy)
        self.button_help_stdout.setToolTip(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.button_help_stdout.setText(_fromUtf8(""))
        self.button_help_stdout.setIcon(icon3)
        self.button_help_stdout.setIconSize(QtCore.QSize(16, 16))
        self.button_help_stdout.setFlat(False)
        self.button_help_stdout.setObjectName(_fromUtf8("button_help_stdout"))
        self.verticalLayout_5.addWidget(self.button_help_stdout)
        self.button_clear_stdout = QtGui.QPushButton(self.widget_3)
        self.button_clear_stdout.setToolTip(QtGui.QApplication.translate("MainWindow", "Clear debug window", None, QtGui.QApplication.UnicodeUTF8))
        self.button_clear_stdout.setText(_fromUtf8(""))
        self.button_clear_stdout.setIcon(icon2)
        self.button_clear_stdout.setIconSize(QtCore.QSize(16, 16))
        self.button_clear_stdout.setObjectName(_fromUtf8("button_clear_stdout"))
        self.verticalLayout_5.addWidget(self.button_clear_stdout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout_6.addWidget(self.widget_3)
        self.verticalLayout_4.addWidget(self.widget_5)
        self.dock_stdout.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dock_stdout)
        self.toolbar_main = QtGui.QToolBar(MainWindow)
        self.toolbar_main.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Main toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolbar_main.setIconSize(QtCore.QSize(32, 32))
        self.toolbar_main.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolbar_main.setFloatable(True)
        self.toolbar_main.setObjectName(_fromUtf8("toolbar_main"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolbar_main)
        self.toolbar_items = toolbar_items(MainWindow)
        self.toolbar_items.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Toolbar items", None, QtGui.QApplication.UnicodeUTF8))
        self.toolbar_items.setObjectName(_fromUtf8("toolbar_items"))
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolbar_items)
        self.action_open = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_open.setIcon(icon4)
        self.action_open.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.action_open.setToolTip(QtGui.QApplication.translate("MainWindow", "Open (Ctrl+0)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_open.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.action_open.setObjectName(_fromUtf8("action_open"))
        self.action_save = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_save.setIcon(icon5)
        self.action_save.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.action_save.setToolTip(QtGui.QApplication.translate("MainWindow", "Save (Control+S)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_save.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.action_save.setObjectName(_fromUtf8("action_save"))
        self.action_save_as = QtGui.QAction(MainWindow)
        self.action_save_as.setIcon(icon5)
        self.action_save_as.setText(QtGui.QApplication.translate("MainWindow", "Save as", None, QtGui.QApplication.UnicodeUTF8))
        self.action_save_as.setToolTip(QtGui.QApplication.translate("MainWindow", "Save as (Control+Shift+S)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_save_as.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+S", None, QtGui.QApplication.UnicodeUTF8))
        self.action_save_as.setObjectName(_fromUtf8("action_save_as"))
        self.action_quit = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/quit_large.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_quit.setIcon(icon6)
        self.action_quit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_quit.setToolTip(QtGui.QApplication.translate("MainWindow", "Quit (Alt+F4)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_quit.setObjectName(_fromUtf8("action_quit"))
        self.action_run = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/run_large.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_run.setIcon(icon7)
        self.action_run.setText(QtGui.QApplication.translate("MainWindow", "Run fullscreen", None, QtGui.QApplication.UnicodeUTF8))
        self.action_run.setToolTip(QtGui.QApplication.translate("MainWindow", "Run fullscreen (Control+R)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_run.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.action_run.setObjectName(_fromUtf8("action_run"))
        self.action_new = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/new_large.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_new.setIcon(icon8)
        self.action_new.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.action_new.setToolTip(QtGui.QApplication.translate("MainWindow", "New (Control+N)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_new.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.action_new.setObjectName(_fromUtf8("action_new"))
        self.action_add_sequence = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/sequence_large.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_add_sequence.setIcon(icon9)
        self.action_add_sequence.setText(QtGui.QApplication.translate("MainWindow", "Add sequence", None, QtGui.QApplication.UnicodeUTF8))
        self.action_add_sequence.setObjectName(_fromUtf8("action_add_sequence"))
        self.action_add_sketchpad = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/sketchpad_large.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_add_sketchpad.setIcon(icon10)
        self.action_add_sketchpad.setText(QtGui.QApplication.translate("MainWindow", "Add sketchpad", None, QtGui.QApplication.UnicodeUTF8))
        self.action_add_sketchpad.setObjectName(_fromUtf8("action_add_sketchpad"))
        self.action_add_keyboard_response = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/keyboard_response_large.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_add_keyboard_response.setIcon(icon11)
        self.action_add_keyboard_response.setText(QtGui.QApplication.translate("MainWindow", "Add keyboard response", None, QtGui.QApplication.UnicodeUTF8))
        self.action_add_keyboard_response.setObjectName(_fromUtf8("action_add_keyboard_response"))
        self.action_add_logger = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/logger_large.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_add_logger.setIcon(icon12)
        self.action_add_logger.setText(QtGui.QApplication.translate("MainWindow", "Add logger", None, QtGui.QApplication.UnicodeUTF8))
        self.action_add_logger.setObjectName(_fromUtf8("action_add_logger"))
        self.action_add_loop = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/loop_large.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_add_loop.setIcon(icon13)
        self.action_add_loop.setText(QtGui.QApplication.translate("MainWindow", "Add loop", None, QtGui.QApplication.UnicodeUTF8))
        self.action_add_loop.setObjectName(_fromUtf8("action_add_loop"))
        self.action_add_feedback = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/feedback_large.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_add_feedback.setIcon(icon14)
        self.action_add_feedback.setText(QtGui.QApplication.translate("MainWindow", "Add feedback", None, QtGui.QApplication.UnicodeUTF8))
        self.action_add_feedback.setObjectName(_fromUtf8("action_add_feedback"))
        self.action_add_inline_script = QtGui.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/inline_script_large.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_add_inline_script.setIcon(icon15)
        self.action_add_inline_script.setText(QtGui.QApplication.translate("MainWindow", "Add inline script", None, QtGui.QApplication.UnicodeUTF8))
        self.action_add_inline_script.setObjectName(_fromUtf8("action_add_inline_script"))
        self.action_close_all_tabs = QtGui.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/close_large.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_close_all_tabs.setIcon(icon16)
        self.action_close_all_tabs.setText(QtGui.QApplication.translate("MainWindow", "Close all tabs", None, QtGui.QApplication.UnicodeUTF8))
        self.action_close_all_tabs.setObjectName(_fromUtf8("action_close_all_tabs"))
        self.action_close_other_tabs = QtGui.QAction(MainWindow)
        self.action_close_other_tabs.setIcon(icon16)
        self.action_close_other_tabs.setText(QtGui.QApplication.translate("MainWindow", "Close other tabs", None, QtGui.QApplication.UnicodeUTF8))
        self.action_close_other_tabs.setToolTip(QtGui.QApplication.translate("MainWindow", "Close other tabs (Control+T)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_close_other_tabs.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+T", None, QtGui.QApplication.UnicodeUTF8))
        self.action_close_other_tabs.setObjectName(_fromUtf8("action_close_other_tabs"))
        self.action_help = QtGui.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/help_large.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_help.setIcon(icon17)
        self.action_help.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.action_help.setObjectName(_fromUtf8("action_help"))
        self.action_about = QtGui.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/about_large.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_about.setIcon(icon18)
        self.action_about.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.action_about.setObjectName(_fromUtf8("action_about"))
        self.action_add_mouse_response = QtGui.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/mouse_response_large.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_add_mouse_response.setIcon(icon19)
        self.action_add_mouse_response.setText(QtGui.QApplication.translate("MainWindow", "Add mouse response", None, QtGui.QApplication.UnicodeUTF8))
        self.action_add_mouse_response.setObjectName(_fromUtf8("action_add_mouse_response"))
        self.action_run_in_window = QtGui.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/window_large.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_run_in_window.setIcon(icon20)
        self.action_run_in_window.setText(QtGui.QApplication.translate("MainWindow", "Run in window", None, QtGui.QApplication.UnicodeUTF8))
        self.action_run_in_window.setToolTip(QtGui.QApplication.translate("MainWindow", "Run in window (Control+W)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_run_in_window.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+W", None, QtGui.QApplication.UnicodeUTF8))
        self.action_run_in_window.setObjectName(_fromUtf8("action_run_in_window"))
        self.action_check_for_update = QtGui.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/update_large.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_check_for_update.setIcon(icon21)
        self.action_check_for_update.setText(QtGui.QApplication.translate("MainWindow", "Check for updates", None, QtGui.QApplication.UnicodeUTF8))
        self.action_check_for_update.setObjectName(_fromUtf8("action_check_for_update"))
        self.action_show_variable_inspector = QtGui.QAction(MainWindow)
        self.action_show_variable_inspector.setCheckable(True)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/variable_inspector_large.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_show_variable_inspector.setIcon(icon22)
        self.action_show_variable_inspector.setText(QtGui.QApplication.translate("MainWindow", "Show variable inspector", None, QtGui.QApplication.UnicodeUTF8))
        self.action_show_variable_inspector.setToolTip(QtGui.QApplication.translate("MainWindow", "Show variable inspector (Control+I)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_show_variable_inspector.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+I", None, QtGui.QApplication.UnicodeUTF8))
        self.action_show_variable_inspector.setObjectName(_fromUtf8("action_show_variable_inspector"))
        self.action_add_sampler = QtGui.QAction(MainWindow)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/sampler_large.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_add_sampler.setIcon(icon23)
        self.action_add_sampler.setText(QtGui.QApplication.translate("MainWindow", "Add sampler", None, QtGui.QApplication.UnicodeUTF8))
        self.action_add_sampler.setToolTip(QtGui.QApplication.translate("MainWindow", "Add sound sampler", None, QtGui.QApplication.UnicodeUTF8))
        self.action_add_sampler.setObjectName(_fromUtf8("action_add_sampler"))
        self.action_add_synth = QtGui.QAction(MainWindow)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/synth_large.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_add_synth.setIcon(icon24)
        self.action_add_synth.setText(QtGui.QApplication.translate("MainWindow", "Add synth", None, QtGui.QApplication.UnicodeUTF8))
        self.action_add_synth.setToolTip(QtGui.QApplication.translate("MainWindow", "Add sound synthesizer", None, QtGui.QApplication.UnicodeUTF8))
        self.action_add_synth.setObjectName(_fromUtf8("action_add_synth"))
        self.action_show_pool = QtGui.QAction(MainWindow)
        self.action_show_pool.setCheckable(True)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/pool_large.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_show_pool.setIcon(icon25)
        self.action_show_pool.setText(QtGui.QApplication.translate("MainWindow", "Show file pool", None, QtGui.QApplication.UnicodeUTF8))
        self.action_show_pool.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.action_show_pool.setObjectName(_fromUtf8("action_show_pool"))
        self.action_show_stdout = QtGui.QAction(MainWindow)
        self.action_show_stdout.setCheckable(True)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/stdout_large.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_show_stdout.setIcon(icon26)
        self.action_show_stdout.setText(QtGui.QApplication.translate("MainWindow", "Show debug window", None, QtGui.QApplication.UnicodeUTF8))
        self.action_show_stdout.setToolTip(QtGui.QApplication.translate("MainWindow", "Show debug window (standard output) and a Python interpreter (Control+D)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_show_stdout.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+D", None, QtGui.QApplication.UnicodeUTF8))
        self.action_show_stdout.setObjectName(_fromUtf8("action_show_stdout"))
        self.action_enable_auto_response = QtGui.QAction(MainWindow)
        self.action_enable_auto_response.setCheckable(True)
        self.action_enable_auto_response.setText(QtGui.QApplication.translate("MainWindow", "Enable auto response", None, QtGui.QApplication.UnicodeUTF8))
        self.action_enable_auto_response.setObjectName(_fromUtf8("action_enable_auto_response"))
        self.actionPlugins = QtGui.QAction(MainWindow)
        self.actionPlugins.setEnabled(False)
        self.actionPlugins.setText(QtGui.QApplication.translate("MainWindow", "Plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlugins.setObjectName(_fromUtf8("actionPlugins"))
        self.action_show_random_tip = QtGui.QAction(MainWindow)
        self.action_show_random_tip.setIcon(icon18)
        self.action_show_random_tip.setText(QtGui.QApplication.translate("MainWindow", "Random tip", None, QtGui.QApplication.UnicodeUTF8))
        self.action_show_random_tip.setToolTip(QtGui.QApplication.translate("MainWindow", "Show a random tip", None, QtGui.QApplication.UnicodeUTF8))
        self.action_show_random_tip.setObjectName(_fromUtf8("action_show_random_tip"))
        self.action_open_autosave_folder = QtGui.QAction(MainWindow)
        self.action_open_autosave_folder.setIcon(icon25)
        self.action_open_autosave_folder.setText(QtGui.QApplication.translate("MainWindow", "Open backup folder", None, QtGui.QApplication.UnicodeUTF8))
        self.action_open_autosave_folder.setObjectName(_fromUtf8("action_open_autosave_folder"))
        self.action_submit_a_bug = QtGui.QAction(MainWindow)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/submit_bug.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_submit_a_bug.setIcon(icon27)
        self.action_submit_a_bug.setText(QtGui.QApplication.translate("MainWindow", "Submit a bug", None, QtGui.QApplication.UnicodeUTF8))
        self.action_submit_a_bug.setObjectName(_fromUtf8("action_submit_a_bug"))
        self.action_contribute = QtGui.QAction(MainWindow)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/contribute.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_contribute.setIcon(icon28)
        self.action_contribute.setText(QtGui.QApplication.translate("MainWindow", "Contribute", None, QtGui.QApplication.UnicodeUTF8))
        self.action_contribute.setObjectName(_fromUtf8("action_contribute"))
        self.action_preferences = QtGui.QAction(MainWindow)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/options_large.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_preferences.setIcon(icon29)
        self.action_preferences.setText(QtGui.QApplication.translate("MainWindow", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.action_preferences.setObjectName(_fromUtf8("action_preferences"))
        self.actionDummy = QtGui.QAction(MainWindow)
        self.actionDummy.setText(QtGui.QApplication.translate("MainWindow", "Dummy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDummy.setObjectName(_fromUtf8("actionDummy"))
        self.action_show_info_in_overview = QtGui.QAction(MainWindow)
        self.action_show_info_in_overview.setCheckable(True)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/item_info_large.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_show_info_in_overview.setIcon(icon30)
        self.action_show_info_in_overview.setText(QtGui.QApplication.translate("MainWindow", "Show info in overview", None, QtGui.QApplication.UnicodeUTF8))
        self.action_show_info_in_overview.setObjectName(_fromUtf8("action_show_info_in_overview"))
        self.menu_recent_files.addAction(self.actionDummy)
        self.menu_file.addAction(self.action_new)
        self.menu_file.addAction(self.action_open)
        self.menu_file.addAction(self.action_save)
        self.menu_file.addAction(self.action_save_as)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.menu_recent_files.menuAction())
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_quit)
        self.menu_run.addAction(self.action_run)
        self.menu_run.addAction(self.action_run_in_window)
        self.menu_run.addSeparator()
        self.menu_run.addAction(self.action_enable_auto_response)
        self.menu_items.addAction(self.action_add_loop)
        self.menu_items.addAction(self.action_add_sequence)
        self.menu_items.addAction(self.action_add_sketchpad)
        self.menu_items.addAction(self.action_add_feedback)
        self.menu_items.addAction(self.action_add_sampler)
        self.menu_items.addAction(self.action_add_synth)
        self.menu_items.addAction(self.action_add_keyboard_response)
        self.menu_items.addAction(self.action_add_mouse_response)
        self.menu_items.addAction(self.action_add_logger)
        self.menu_items.addAction(self.action_add_inline_script)
        self.menu_items.addSeparator()
        self.menu_items.addAction(self.actionPlugins)
        self.menu_view.addAction(self.action_close_all_tabs)
        self.menu_view.addAction(self.action_close_other_tabs)
        self.menu_view.addAction(self.action_show_info_in_overview)
        self.menu_view.addSeparator()
        self.menu_view.addAction(self.action_show_variable_inspector)
        self.menu_view.addAction(self.action_show_pool)
        self.menu_view.addAction(self.action_show_stdout)
        self.menu_help.addAction(self.action_help)
        self.menu_help.addAction(self.action_show_random_tip)
        self.menu_help.addSeparator()
        self.menu_help.addAction(self.action_submit_a_bug)
        self.menu_help.addAction(self.action_contribute)
        self.menu_help.addSeparator()
        self.menu_help.addAction(self.action_about)
        self.menu_tools.addAction(self.action_check_for_update)
        self.menu_tools.addAction(self.action_open_autosave_folder)
        self.menu_tools.addSeparator()
        self.menu_tools.addAction(self.action_preferences)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_run.menuAction())
        self.menubar.addAction(self.menu_items.menuAction())
        self.menubar.addAction(self.menu_view.menuAction())
        self.menubar.addAction(self.menu_tools.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())
        self.toolbar_main.addAction(self.action_new)
        self.toolbar_main.addAction(self.action_open)
        self.toolbar_main.addAction(self.action_save)
        self.toolbar_main.addSeparator()
        self.toolbar_main.addAction(self.action_run)
        self.toolbar_main.addAction(self.action_run_in_window)
        self.toolbar_main.addSeparator()
        self.toolbar_main.addAction(self.action_close_other_tabs)
        self.toolbar_main.addAction(self.action_show_info_in_overview)
        self.toolbar_main.addSeparator()
        self.toolbar_main.addAction(self.action_show_pool)
        self.toolbar_main.addAction(self.action_show_variable_inspector)
        self.toolbar_main.addAction(self.action_show_stdout)
        self.toolbar_main.addSeparator()
        self.toolbar_main.addAction(self.action_help)

        self.retranslateUi(MainWindow)
        self.tabwidget.setCurrentIndex(-1)
        QtCore.QObject.connect(self.button_variables_clear, QtCore.SIGNAL(_fromUtf8("clicked()")), self.edit_variable_filter.clear)
        QtCore.QObject.connect(self.button_clear_stdout, QtCore.SIGNAL(_fromUtf8("clicked()")), self.edit_stdout.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.table_variables.setSortingEnabled(True)
        item = self.table_variables.horizontalHeaderItem(0)
        item = self.table_variables.horizontalHeaderItem(1)
        item = self.table_variables.horizontalHeaderItem(2)

from statusbar import statusbar
from variable_inspector import variable_inspector
from tree_overview import tree_overview
from pyterm import console
from toolbar_items import toolbar_items
import icons_rc
